// Package main generates the LynxFlow golden transcript .test files by
// translating existing SPL2 transcripts. It writes .test files only;
// .expected files are generated by running the golden tests with -update.
//
// Usage:
//
//	go run ./internal/testgen/lynxflow
package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/lynxbase/lynxdb/pkg/lynxflow/translate"
)

type testFile struct {
	Name     string
	File     string // # file: header (file mode only)
	Format   string
	ExitCode string
	Skip     string
	Query    string
}

func parseTestFile(path string) (testFile, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return testFile{}, err
	}

	base := filepath.Base(path)
	name := strings.TrimSuffix(base, ".test")

	tc := testFile{
		Name:     name,
		Format:   "json",
		ExitCode: "0",
	}

	var queryLines []string
	scanner := bufio.NewScanner(strings.NewReader(string(data)))
	for scanner.Scan() {
		line := scanner.Text()
		if strings.HasPrefix(line, "# ") {
			header := strings.TrimPrefix(line, "# ")
			if k, v, ok := strings.Cut(header, ":"); ok {
				k = strings.TrimSpace(k)
				v = strings.TrimSpace(v)
				switch k {
				case "file":
					tc.File = v
				case "format":
					tc.Format = v
				case "exit":
					tc.ExitCode = v
				case "skip":
					tc.Skip = v
				}
				continue
			}
		}
		queryLines = append(queryLines, line)
	}

	tc.Query = strings.TrimSpace(strings.Join(queryLines, "\n"))
	return tc, nil
}

type skipRecord struct {
	Name   string
	Reason string
}

func processDir(srcDir, dstDir, subdir string) (translated int, skipped []skipRecord) {
	entries, err := os.ReadDir(srcDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "ERROR: read %s: %v\n", srcDir, err)
		return
	}

	os.MkdirAll(dstDir, 0o755)

	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".test") {
			continue
		}

		tc, err := parseTestFile(filepath.Join(srcDir, e.Name()))
		if err != nil {
			skipped = append(skipped, skipRecord{tc.Name, err.Error()})
			continue
		}

		if tc.ExitCode != "0" {
			skipped = append(skipped, skipRecord{tc.Name, "error test (non-zero exit code)"})
			continue
		}
		if strings.Contains(tc.Name, "lynxflow") {
			skipped = append(skipped, skipRecord{tc.Name, "already a lynxflow test"})
			continue
		}
		if tc.Skip != "" {
			skipped = append(skipped, skipRecord{tc.Name, "skip: " + tc.Skip})
			continue
		}
		if subdir == "file" && tc.File == "" {
			skipped = append(skipped, skipRecord{tc.Name, "file mode test without # file: header"})
			continue
		}

		lfQuery, notes, err := translate.SPL2ToLynxFlow(tc.Query)
		if err != nil {
			skipped = append(skipped, skipRecord{tc.Name, err.Error()})
			continue
		}

		// Write .test file.
		var sb strings.Builder
		if tc.File != "" {
			fmt.Fprintf(&sb, "# file: %s\n", tc.File)
		}
		fmt.Fprintf(&sb, "# format: %s\n", tc.Format)
		sb.WriteString("# language: lynxflow\n")
		sb.WriteString(lfQuery)

		outPath := filepath.Join(dstDir, tc.Name+".test")
		if err := os.WriteFile(outPath, []byte(sb.String()), 0o644); err != nil {
			fmt.Fprintf(os.Stderr, "ERROR: write %s: %v\n", outPath, err)
			continue
		}

		translated++
		if len(notes) > 0 {
			for _, n := range notes {
				fmt.Fprintf(os.Stderr, "NOTE %s: [%s] %s\n", tc.Name, n.Code, n.Message)
			}
		}
	}
	return
}

func writeSkippedMD(outRoot string, skipped []skipRecord) error {
	if len(skipped) == 0 {
		return nil
	}

	groups := map[string][]skipRecord{}
	for _, s := range skipped {
		groupKey := s.Reason
		if strings.HasPrefix(groupKey, "translate.SPL2ToLynxFlow") {
			if idx := strings.LastIndex(groupKey, "unsupported command"); idx > 0 {
				groupKey = strings.TrimSpace(groupKey[idx:])
				if paren := strings.Index(groupKey, "("); paren > 0 && paren < 60 {
					groupKey = strings.TrimSpace(groupKey[:paren])
				}
			} else {
				groupKey = "translation error"
			}
		} else if strings.Contains(groupKey, "lynxflow query failed") {
			groupKey = "lynxflow runtime error"
		}
		groups[groupKey] = append(groups[groupKey], s)
	}

	var keys []string
	for k := range groups {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var sb strings.Builder
	sb.WriteString("# Skipped Transcripts\n\n")
	sb.WriteString(fmt.Sprintf("Total skipped: %d\n\n", len(skipped)))
	for _, k := range keys {
		entries := groups[k]
		sb.WriteString(fmt.Sprintf("## %s (%d)\n\n", k, len(entries)))
		for _, e := range entries {
			sb.WriteString(fmt.Sprintf("- `%s`: %s\n", e.Name, e.Reason))
		}
		sb.WriteByte('\n')
	}

	return os.WriteFile(filepath.Join(outRoot, "SKIPPED.md"), []byte(sb.String()), 0o644)
}

func main() {
	// Find project root.
	wd, err := os.Getwd()
	if err != nil {
		fmt.Fprintf(os.Stderr, "FATAL: %v\n", err)
		os.Exit(1)
	}

	// Walk up to find go.mod.
	root := wd
	for {
		if _, err := os.Stat(filepath.Join(root, "go.mod")); err == nil {
			break
		}
		parent := filepath.Dir(root)
		if parent == root {
			fmt.Fprintln(os.Stderr, "FATAL: cannot find project root (go.mod)")
			os.Exit(1)
		}
		root = parent
	}

	outRoot := filepath.Join(root, "testdata", "cli-lynxflow")
	// Do NOT RemoveAll — preserve existing .expected files from previous -update runs.
	// Only .test files are (re)written.

	var allSkipped []skipRecord
	totalTranslated := 0
	totalTests := 0

	for _, sub := range []string{"file", "server"} {
		srcDir := filepath.Join(root, "testdata", "cli", sub)
		dstDir := filepath.Join(outRoot, sub)

		// Count total tests.
		entries, _ := os.ReadDir(srcDir)
		for _, e := range entries {
			if !e.IsDir() && strings.HasSuffix(e.Name(), ".test") {
				totalTests++
			}
		}

		n, skipped := processDir(srcDir, dstDir, sub)
		totalTranslated += n
		allSkipped = append(allSkipped, skipped...)
	}

	if err := writeSkippedMD(outRoot, allSkipped); err != nil {
		fmt.Fprintf(os.Stderr, "ERROR: write SKIPPED.md: %v\n", err)
	}

	pct := float64(totalTranslated) / float64(totalTests) * 100
	fmt.Printf("Total transcripts: %d\n", totalTests)
	fmt.Printf("Translated (test files written): %d (%.1f%%)\n", totalTranslated, pct)
	fmt.Printf("Skipped: %d\n", len(allSkipped))
	fmt.Printf("\nOutput: %s\n", outRoot)
	fmt.Println("\nNext steps:")
	fmt.Println("  1. go test -tags clitest -run TestGoldenLynxFlow_File -update -timeout 10m ./test/cli/")
	fmt.Println("  2. go test -tags clitest -run TestGoldenLynxFlow_Server -update -timeout 10m ./test/cli/")
	fmt.Println("  These will record .expected files by running the translated queries.")
}
