package registry

// aggregates is the frozen v1 aggregate and window-function surface
// (RFC-002 §10). The percN alias family replaces the RFC-001 percentile zoo.
var aggregates = []Aggregate{
	{Name: "count", Params: []Param{{Name: "x", Type: TAny, Optional: true}}, SupportsWhere: true, Result: TInt, Doc: "count() counts rows; count(x) counts non-null x; count(where p) counts matching rows."},
	{Name: "sum", Params: []Param{{Name: "x", Type: TNumber}}, SupportsWhere: true, Result: TNumber, Doc: "Nulls skipped; all-null group yields null."},
	{Name: "avg", Params: []Param{{Name: "x", Type: TNumber}}, SupportsWhere: true, Result: TFloat},
	{Name: "min", Params: []Param{{Name: "x", Type: TAny}}, SupportsWhere: true, Result: TAny},
	{Name: "max", Params: []Param{{Name: "x", Type: TAny}}, SupportsWhere: true, Result: TAny},
	{Name: "dc", Params: []Param{{Name: "x", Type: TAny}}, SupportsWhere: true, Result: TInt, Doc: "Distinct count; exact below 10K, HLL above."},
	{Name: "estdc", Params: []Param{{Name: "x", Type: TAny}}, SupportsWhere: true, Result: TInt, Doc: "Always-HLL distinct count."},
	{Name: "perc", Params: []Param{{Name: "x", Type: TNumber}, {Name: "p", Type: TNumber}}, SupportsWhere: true, Result: TFloat, Doc: "T-digest percentile; p in [0, 100]."},
	{Name: "p50", Params: []Param{{Name: "x", Type: TNumber}}, SupportsWhere: true, Result: TFloat, Doc: "Alias for perc(x, 50)."},
	{Name: "p75", Params: []Param{{Name: "x", Type: TNumber}}, SupportsWhere: true, Result: TFloat, Doc: "Alias for perc(x, 75)."},
	{Name: "p90", Params: []Param{{Name: "x", Type: TNumber}}, SupportsWhere: true, Result: TFloat, Doc: "Alias for perc(x, 90)."},
	{Name: "p95", Params: []Param{{Name: "x", Type: TNumber}}, SupportsWhere: true, Result: TFloat, Doc: "Alias for perc(x, 95)."},
	{Name: "p99", Params: []Param{{Name: "x", Type: TNumber}}, SupportsWhere: true, Result: TFloat, Doc: "Alias for perc(x, 99)."},
	{Name: "perc_weighted", Params: []Param{{Name: "x", Type: TNumber}, {Name: "weight", Type: TNumber}, {Name: "p", Type: TNumber}}, SupportsWhere: true, Result: TFloat, Doc: "Weighted t-digest percentile; p in [0, 100]."},
	{Name: "stdev", Params: []Param{{Name: "x", Type: TNumber}}, SupportsWhere: true, Result: TFloat, Doc: "Sample standard deviation."},
	{Name: "var", Params: []Param{{Name: "x", Type: TNumber}}, SupportsWhere: true, Result: TFloat, Doc: "Sample variance."},
	{Name: "corr", Params: []Param{{Name: "x", Type: TNumber}, {Name: "y", Type: TNumber}}, SupportsWhere: true, Result: TFloat, Doc: "Pearson correlation over rows where both arguments are numeric."},
	{Name: "covar", Params: []Param{{Name: "x", Type: TNumber}, {Name: "y", Type: TNumber}}, SupportsWhere: true, Result: TFloat, Doc: "Sample covariance over rows where both arguments are numeric."},
	{Name: "linear_fit", Params: []Param{{Name: "x", Type: TNumber}, {Name: "y", Type: TNumber}}, SupportsWhere: true, Result: TObject, Doc: "Least-squares fit as {slope, intercept, r2}."},
	{Name: "sum_object", Params: []Param{{Name: "obj", Type: TObject}}, SupportsWhere: true, Result: TObject, Doc: "Per-key sums for numeric object values."},
	{Name: "skewness", Params: []Param{{Name: "x", Type: TNumber}}, SupportsWhere: true, Result: TFloat, Doc: "Bias-corrected sample skewness."},
	{Name: "kurtosis", Params: []Param{{Name: "x", Type: TNumber}}, SupportsWhere: true, Result: TFloat, Doc: "Bias-corrected sample excess kurtosis."},
	{Name: "mad", Params: []Param{{Name: "x", Type: TNumber}}, SupportsWhere: true, Result: TFloat, Doc: "Median absolute deviation over numeric values."},
	{Name: "mode", Params: []Param{{Name: "x", Type: TAny}}, SupportsWhere: true, Result: TAny},
	{Name: "arg_max", Params: []Param{{Name: "value", Type: TAny}, {Name: "order", Type: TAny}}, SupportsWhere: true, Result: TAny, Doc: "Value from the row with the greatest order expression."},
	{Name: "arg_min", Params: []Param{{Name: "value", Type: TAny}, {Name: "order", Type: TAny}}, SupportsWhere: true, Result: TAny, Doc: "Value from the row with the least order expression."},
	{Name: "any_value", Params: []Param{{Name: "x", Type: TAny}}, SupportsWhere: true, Result: TAny, Doc: "An arbitrary non-null value from the group."},
	{Name: "top_k", Params: []Param{{Name: "x", Type: TAny}, {Name: "k", Type: TInt}}, SupportsWhere: true, Result: TArray, Doc: "Top k non-null values with counts."},
	{Name: "top_k_weighted", Params: []Param{{Name: "x", Type: TAny}, {Name: "weight", Type: TNumber}, {Name: "k", Type: TInt}}, SupportsWhere: true, Result: TArray, Doc: "Top k non-null values by summed positive weight."},
	{Name: "value_counts", Params: []Param{{Name: "x", Type: TAny}, {Name: "max", Type: TInt, Optional: true}}, SupportsWhere: true, Result: TArray, Doc: "Non-null values with counts, sorted by frequency and optionally capped."},
	{Name: "avg_weighted", Params: []Param{{Name: "x", Type: TNumber}, {Name: "weight", Type: TNumber}}, SupportsWhere: true, Result: TFloat, Doc: "Weighted average as sum(x * weight) / sum(weight)."},
	{Name: "entropy", Params: []Param{{Name: "x", Type: TAny}}, SupportsWhere: true, Result: TFloat, Doc: "Shannon entropy of non-null values, in bits."},
	{Name: "max_n", Params: []Param{{Name: "x", Type: TAny}, {Name: "n", Type: TInt}}, SupportsWhere: true, Result: TArray, Doc: "Largest n non-null values."},
	{Name: "min_n", Params: []Param{{Name: "x", Type: TAny}, {Name: "n", Type: TInt}}, SupportsWhere: true, Result: TArray, Doc: "Smallest n non-null values."},
	{Name: "first", Params: []Param{{Name: "x", Type: TAny}}, SupportsWhere: true, Result: TAny, Doc: "First non-null in row order."},
	{Name: "last", Params: []Param{{Name: "x", Type: TAny}}, SupportsWhere: true, Result: TAny, Doc: "Last non-null in row order."},
	{Name: "earliest", Params: []Param{{Name: "x", Type: TAny}}, SupportsWhere: true, Result: TAny, Doc: "Value from the row with the smallest _time."},
	{Name: "latest", Params: []Param{{Name: "x", Type: TAny}}, SupportsWhere: true, Result: TAny, Doc: "Value from the row with the largest _time."},
	{Name: "values", Params: []Param{{Name: "x", Type: TAny}, {Name: "n", Type: TInt, Optional: true}}, SupportsWhere: true, Result: TArray, Doc: "Distinct non-null values, optionally capped at n."},
	{Name: "list", Params: []Param{{Name: "x", Type: TAny}, {Name: "n", Type: TInt, Optional: true}}, SupportsWhere: true, Result: TArray, Doc: "All non-null values in row order, optionally capped at n."},
	{Name: "rate", SupportsWhere: true, Result: TFloat, Doc: "Row count divided by the group's time-bucket span."},
	{Name: "per_second", Params: []Param{{Name: "x", Type: TNumber}}, SupportsWhere: true, Result: TFloat, Doc: "sum(x) divided by the group's time-bucket span in seconds."},

	// window (streamstats only)
	{Name: "lag", Params: []Param{{Name: "x", Type: TAny}, {Name: "n", Type: TInt, Optional: true}}, WindowOnly: true, Result: TAny, Doc: "Value n rows back (default 1)."},
	{Name: "lead", Params: []Param{{Name: "x", Type: TAny}, {Name: "n", Type: TInt, Optional: true}}, WindowOnly: true, Result: TAny, Doc: "Value n rows ahead (default 1)."},
	{Name: "row_number", WindowOnly: true, Result: TInt, Doc: "1-based row index within the group."},
	{Name: "running_sum", Params: []Param{{Name: "x", Type: TNumber}}, WindowOnly: true, Result: TNumber},
	{Name: "moving_avg", Params: []Param{{Name: "x", Type: TNumber}, {Name: "n", Type: TInt}}, WindowOnly: true, Result: TFloat},
	{Name: "delta", Params: []Param{{Name: "x", Type: TNumber}}, WindowOnly: true, Result: TFloat, Doc: "Difference between the current value and previous group value."},
}
